security:
    encoders:
        CreditJeeves\DataBundle\Entity\User:
            id: user.security.encoder.digest

    role_hierarchy:
        ROLE_USER:     ROLE_USER
        ROLE_DEALER:   ROLE_DEALER
        ROLE_ADMIN:    ROLE_ADMIN

    providers:
        custom:
            id: fos_user.user_provider.username_email

    firewalls:
        api:
            pattern: ^/api
            fos_oauth: true
            stateless: true
            anonymous: false
        oauth_token:
            pattern: ^/oauth/v2/token
            #security: false
            anonymous: true
        main:
            pattern: ^/
            form_login:
                provider: custom 
                csrf_provider: form.csrf_provider
                success_handler: user.service.login_success_handler
                failure_handler: user.service.login_failure_handler
            logout:       true
            anonymous:    true


    access_control:
        - { path: ^/oauth/v2/token,           role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/applicant/*,          roles: [IS_AUTHENTICATED_FULLY, CREDIT_API]}
        - { path: ^/api/enroll,               roles: [IS_AUTHENTICATED_FULLY, CREDIT_API]}
        - { path: ^/api/applicants/verify,    roles: [IS_AUTHENTICATED_FULLY, USE_QUITY_API]}
        - { path: ^/back_to_admin$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_behat/tests/,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler/,     role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js/*,           role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css/*,          role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt/,          role: IS_AUTHENTICATED_ANONYMOUSLY }        
        - { path: ^/_profiler/,     role: ROLE_USER }
        - { path: ^/_profiler/,     role: ROLE_DEALER }
        - { path: ^/_profiler/,     role: ROLE_ADMIN }
        - { path: ^/test,           role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$,         role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/landlord/ajax/property/add$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting,      role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/new$,           role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/new/,           role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/invite,         role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/message,        role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/public/*,       role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login/defence/*,   role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/documentation/api, role: ROLE_ADMIN  }
        - { path: ^/admin/,         role: ROLE_ADMIN }
        - { path: ^/dealer/,        role: ROLE_DEALER }
        - { path: ^/,               role: ROLE_USER }
        

# We'll additional pages
#       - { path: ^/register,   role: IS_AUTHENTICATED_ANONYMOUSLY }
#       - { path: ^/resetting,  role: IS_AUTHENTICATED_ANONYMOUSLY }
