payment_accounts:
  type:         rest
  resource:     "@RjApiBundle/Controller/Tenant/PaymentAccountsController.php"
  name_prefix:  api_

units:
  type:         rest
  resource:     "@RjApiBundle/Controller/Tenant/UnitsController.php"
  name_prefix:  api_

payments:
  type:         rest
  resource:     "@RjApiBundle/Controller/Tenant/PaymentsController.php"
  name_prefix:  api_

contracts:
  type:         rest
  resource:     "@RjApiBundle/Controller/Tenant/ContractsController.php"
  name_prefix:  api_

orders:
  type:         rest
  resource:     "@RjApiBundle/Controller/Tenant/OrdersController.php"
  name_prefix:  api_

addresses:
  type:         rest
  resource:     "@RjApiBundle/Controller/Tenant/AddressesController.php"
  name_prefix:  api_

tenant:
  type:         rest
  resource:     "@RjApiBundle/Controller/Tenant/TenantController.php"
  name_prefix:  api_

