imports:
    - { resource: config_dev.yml }

parameters:
    router.request_context.base_url: '/rj_test.php'
    doctrine.dbal.connection.wrapper_class: 'CreditJeeves\TestBundle\Doctrine\DBAL\PersistedConnection'

    payment_report_path: 'src/RentJeeves/CheckoutBundle/Tests/Fixtures/hps'

    credit_services:
        credit_summary_vendor: experian # supported values are 'transunion' or 'experian'

framework:
    router:   { resource: "%kernel.root_dir%/config/rj/routing_test.yml" }
    translator: { fallback: 'test' }
    default_locale: 'test'
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    transport: file

doctrine:
    dbal:
        dbname:   '%database_name%_test'

twig:
    strict_variables: true

mink:
    goutte: ~
#    sahi: ~
    zombie: ~
#    selenium: ~
    selenium2: ~

backup_restore: ~
