imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/rj/routing_dev.yml" }
    profiler: { only_exceptions: false }
    session:
        cookie_secure: false
        cookie_httponly: false

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    channels: ["import"]
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info
        doctrine:
            type:  stream
            action_level: info
            path:  %kernel.logs_dir%/%kernel.environment%_doctrine.log
            channels: doctrine

khepin_yaml_fixtures:
    resources:
        - DataBundle
        - RjDataBundle
    directory: Resources/fixtures
    datetime_class: 'RentJeeves\CoreBundle\DateTime'

backup_restore: ~
