admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix:   /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

admin_common:
    resource: "@RjAdminBundle/Controller"
    type:     annotation
    prefix:   /admin

landlord:
    resource: "@LandlordBundle/Controller/"
    type:     annotation
    prefix:   /landlord

tenant:
    resource: "@TenantBundle/Controller/"
    type:     annotation
    prefix:   /

checkout:
    resource: "@CheckoutBundle/Controller/"
    type:     annotation
    prefix:   /

ExperianBundle:
    resource: "@ExperianBundle/Controller/"
    type:     annotation
    prefix:   /

RjExperianBundle:
    resource: "@RjExperianBundle/Controller/"
    type:     annotation
    prefix:   /

public:
    resource: "@PublicBundle/Controller"
    type:     annotation
    prefix:   /

RjPublicBundle:
    resource: "@RjPublicBundle/Controller/"
    type:     annotation
    prefix:   /

core:
    resource: "@CoreBundle/Controller"
    type:     annotation

RjCheckoutBundle:
    resource: "@RjCheckoutBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

trustedLandlord:
    resource: "@TrustedLandlordBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:   /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:   /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix:   /resetting

fos_user_resetting_request:
    path:     /resetting
    defaults:
        _controller: FOSUserBundle:Resetting:request
        _method:     GET

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix:   /profile

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_apy_jsformvalidation:
    resource: "@APYJsFormValidationBundle/Resources/config/routing/routing.yml"

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

fos_security:
    resource: "@UserBundle/Controller/SecurityController.php"
    type:     annotation

jms_jobs_details:
    defaults: { _controller: JMSJobQueueBundle:Job:details }
    path: /admin/job/{id}

jms_jobs_overview:
    path: /admin/job/list

jms_jobs_retry_job:
    defaults: { _controller: JMSJobQueueBundle:Job:retryJob }
    path: /admin/job/{id}/retryJob

jms_jobs_cancel_job:
    defaults: { _controller: JMSJobQueueBundle:Job:cancelJob }
    path: /admin/job/{id}/cancel

#REST
rest_api_tenant_v1:
  type : rest
  resource: "@RjApiBundle/Resources/config/routing_tenant.yml"
  prefix: /api/tenant

rest_api_partner:
  type : rest
  resource: "@RjApiBundle/Resources/config/routing_partner.yml"
  prefix: /api/partner


NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /documentation/api

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

oauth_server_security:
    resource: "@OAuthServerBundle/Controller/"
    type:     annotation
    prefix:   /
