#FOSUserBundle
fos_user:
    db_driver: ormÂ 
    firewall_name: main
    user_class: CreditJeeves\DataBundle\Entity\User
    service:
        mailer: project.mailer
    from_email:
        address:        support@creditjeeves.com
        sender_name:    CreditJeeves
    registration:
        confirmation:
            enabled:    true
            template: 'registration'
    resetting:
        email:
            template: 'resetting'